creation_rules:
  - path_regex: '.*/k0s-github-arc/.*\.yaml'
    encrypted_regex: '^(data|stringData)$'
    age: 'age13qg6tpdjfjxcucc9v0lprl2q8wfzvstamh6a6zhnmedq835f3ehsc56thu,age1f8vgexpv2fs0yhjes9tqn0rum4j7l0lxupxk66nn7jpa6cyh3etsqqd0ee'
  - path_regex: '.*/k0s-infra/.*sops.yaml'
    encrypted_regex: '^(data|stringData)$'
    age: 'age13qg6tpdjfjxcucc9v0lprl2q8wfzvstamh6a6zhnmedq835f3ehsc56thu,age1f8vgexpv2fs0yhjes9tqn0rum4j7l0lxupxk66nn7jpa6cyh3etsqqd0ee'
  - path_regex: 'secrets.yaml'
    age: 'age1f8vgexpv2fs0yhjes9tqn0rum4j7l0lxupxk66nn7jpa6cyh3etsqqd0ee'
