FROM ghcr.io/niule-eu/homelab/tools:latest

ARG USERID
ARG GROUPID
ARG USERNAME

USER 0

# create container user
RUN <<EOF /bin/bash
    set -eux
    groupadd --gid ${GROUPID} ${USERNAME}
    useradd --create-home --shell /bin/bash --uid ${USERID} --gid ${GROUPID} ${USERNAME}
    mkdir -p /home/$USERNAME/.config/sops/age
    chown -R $USERNAME:$USERNAME /home/$USERNAME/.config/
EOF

# persist container user command history
RUN <<EOF /bin/bash
    set -eux
    mkdir -p /commandhistory
    touch /commandhistory/.bash_history
    chown -R ${USERNAME} /commandhistory
    echo "export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" >> /home/${USERNAME}/.bashrc
EOF

USER $USERNAME

# Setup vibe cli
RUN <<"EOF" /bin/bash
    set -eux
    uv tool install mistral-vibe
EOF

COPY --chown=$USERNAME:$USERNAME podman-connections.json /home/$USERNAME/.config/containers/podman-connections.json

COPY --chown=$USERNAME:$USERNAME <<podman-alias <<"podman-completion" <<"gopath-bin" <<"dnscontrol-completion" <<"vibe" /home/$USERNAME/.bashrc.d/
    alias podman='podman-remote'
podman-alias
    eval "$(podman completion bash)"
podman-completion
    export PATH=$PATH:$GOPATH/bin
gopath-bin
    eval "$(dnscontrol shell-completion bash)"
dnscontrol-completion
    alias vibe='MISTRAL_API_KEY=$(sops decrypt --extract "[\"MISTRAL_API_KEY\"]" secrets.yaml) vibe'
vibe
