# Download golang and extract to tmp
FROM curlimages/curl:latest as golang

# For github assets, and generally a good idea:
# curl -H "Accept: application/octet-stream"

ARG GOLANG_URL
ARG GOLANG_HASH

RUN <<EOF /bin/sh
    set -eux
    curl -H "Accept: application/octet-stream" -Lo go.tar.gz ${GOLANG_URL}
    echo "${GOLANG_HASH} go.tar.gz" | sha256sum -c
    tar -C /tmp/ -xzf go.tar.gz
EOF

# Download sops and move to /tmp
FROM curlimages/curl:latest as sops

ARG GETSOPS_SOPS_URL
ARG GETSOPS_SOPS_HASH

RUN <<EOF /bin/sh
    set -eux
    curl -H "Accept: application/octet-stream" -Lo sops ${GETSOPS_SOPS_URL}
    echo "${GETSOPS_SOPS_HASH} sops" | sha256sum -c
    mv sops /tmp/sops
EOF

# Download opentofu and move to /tmp
FROM curlimages/curl:latest as opentofu

ARG OPENTOFU_OPENTOFU_URL
ARG OPENTOFU_OPENTOFU_HASH

RUN <<EOF /bin/sh
    set -eux
    curl -H "Accept: application/octet-stream" -Lo opentofu.tar.gz ${OPENTOFU_OPENTOFU_URL}
    echo "${OPENTOFU_OPENTOFU_HASH} opentofu.tar.gz" | sha256sum -c
    tar -C /tmp/ -xzf opentofu.tar.gz
EOF

# Download podman-remote and move to /tmp
FROM curlimages/curl:latest as podman-remote

ARG CONTAINERS_PODMAN_URL
ARG CONTAINERS_PODMAN_HASH

RUN <<EOF /bin/sh
    set -eux
    curl -H "Accept: application/octet-stream" -Lo podman-remote.tar.gz ${CONTAINERS_PODMAN_URL}
    echo "${CONTAINERS_PODMAN_HASH} podman-remote.tar.gz" | sha256sum -c
    tar -C /tmp/ -xzf podman-remote.tar.gz
EOF

# Download pkl and move to /tmp
FROM curlimages/curl:latest as pkl

ARG APPLE_PKL_URL

RUN <<EOF /bin/sh
    set -eux
    curl -H "Accept: application/octet-stream" -Lo pkl ${APPLE_PKL_URL}
    chmod +x pkl
    mv pkl /tmp/pkl    
EOF

FROM docker.io/eclipse-temurin:22.0.2_9-jdk-ubi9-minimal as java

# Download dnscontrol and move to /tmp
FROM curlimages/curl:latest as dnscontrol

ARG STACKEXCHANGE_DNSCONTROL_URL
ARG STACKEXCHANGE_DNSCONTROL_HASH

RUN <<EOF /bin/sh
    set -eux
    curl -H "Accept: application/octet-stream" -Lo dnscontrol.tar.gz ${STACKEXCHANGE_DNSCONTROL_URL}
    echo "${STACKEXCHANGE_DNSCONTROL_HASH} dnscontrol.tar.gz" | sha256sum -c
    tar -C /tmp/ -xzf dnscontrol.tar.gz
    rm -rf dnscontrol.tar.gz
EOF

# Download sd and move to /tmp
FROM curlimages/curl:latest as sd

ARG CHMLN_SD_URL

RUN <<EOF /bin/sh
    set -eux
    curl -H "Accept: application/octet-stream" -Lo sd.tar.gz ${CHMLN_SD_URL}
    tar -C /tmp/ -xzf sd.tar.gz --strip-components 1
    rm -rf sd.tar.gz
EOF

FROM fedora-minimal:42

ARG USERID
ARG GROUPID
ARG USERNAME

RUN dnf update -y && dnf install -y --setopt=install_weak_deps=False \
    git \
    bash-completion \
    tar \
    bzip2 \
    gzip \
    butane \
    yq jq

COPY --chown=root:root --chmod=0755 --from=golang /tmp/go /usr/local/go
COPY --chown=root:root --chmod=0755 --from=sops /tmp/sops /usr/local/bin/
COPY --chown=root:root --chmod=0755 --from=opentofu /tmp/tofu /usr/local/bin/
COPY --chown=root:root --chmod=0755 --from=podman-remote /tmp/bin/podman* /usr/local/bin/podman-remote
COPY --chown=root:root --chmod=0755 --from=pkl /tmp/pkl /usr/local/bin/
COPY --chown=root:root --chmod=0755 --from=java  /opt/java /opt/java
COPY --chown=root:root --chmod=0755 --from=dnscontrol /tmp/dnscontrol /usr/local/bin/
COPY --chown=root:root --chmod=0755 --from=sd /tmp/sd /usr/local/bin/
COPY --chown=root:root --chmod=0644 --from=sd /tmp/completions/sd.bash /usr/share/bash-completion/completions/sd

# create container user
RUN <<EOF /bin/bash
    set -eux
    groupadd --gid ${GROUPID} ${USERNAME}
    useradd --create-home --shell /bin/bash --uid ${USERID} --gid ${GROUPID} ${USERNAME}
EOF

# Add go to path and adjust permissons
# Note the quotes around "EOF", they tell the container builder not to interpolate ARGs into the script
RUN <<"EOF" /bin/bash -s ${USERNAME}
    echo 'export PATH="/usr/local/go/bin:$PATH"' > /etc/profile.d/go_lang.sh
    mkdir -p /home/$USERNAME/.config/sops/age
    chown -R $USERNAME:$USERNAME /home/$USERNAME/.config/
EOF


# persist container user command history
RUN <<EOF /bin/bash
    set -eux
    mkdir -p /commandhistory
    touch /commandhistory/.bash_history
    chown -R ${USERNAME} /commandhistory
    echo "export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" >> /home/${USERNAME}/.bashrc
EOF

USER $USERNAME

ENV PATH="$PATH:/opt/java/openjdk/bin"

COPY --chown=$USERNAME:$USERNAME <<EOF /home/$USERNAME/.config/containers/podman-connections.json
    {
      "Connection": { 
        "Default": "host",
          "Connections": { 
            "host": {
              "URI": "unix://run/user/2000/podman/podman.sock"
            }
          }
      },
      "Farm": {}
    }
EOF

COPY --chown=$USERNAME:$USERNAME <<podman-alias <<"gopath-bin" <<"dnscontrol-completion" /home/$USERNAME/.bashrc.d/
    alias podman='podman-remote'
podman-alias
    export PATH=$PATH:$GOPATH/bin
gopath-bin
    eval "$(dnscontrol shell-completion bash)"
dnscontrol-completion

