FROM ghcr.io/mgoltzsche/podman:{{.PodmanRemoteVersion}}-remote AS podman-remote
FROM docker.io/codercom/code-server:{{.CodeServerVersion}}

USER root

COPY --from=podman-remote /usr/local/bin/podman-remote /usr/local/bin/podman

RUN userdel -r coder || true

RUN groupadd -g {{.UserGID}} devpodman && \
    useradd -m -u {{.UserUID}} -g {{.UserGID}} -s /bin/bash devpodman

COPY devpodman-shell /usr/local/bin/devpodman-shell

RUN chmod +x /usr/local/bin/devpodman-shell

USER devpodman

RUN mkdir -p /home/devpodman/.config /home/devpodman/.local /home/devpodman/.local/share/code-server/User

COPY settings.json /home/devpodman/.local/share/code-server/User/settings.json

WORKDIR /workspace

ENTRYPOINT ["code-server"]
