ARG KEA_DHCPV4_TAG=3.1.5
ARG KEA_HOOKS_TAG=3.1.5

FROM docker.io/jonasal/kea-hooks:$KEA_HOOKS_TAG as hooks

FROM docker.io/jonasal/kea-dhcp4-slim:$KEA_DHCPV4_TAG

COPY --from=hooks /hooks/libdhcp_pgsql.so /usr/local/lib/kea/hooks

RUN ldconfig