// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package model

// Mount definition for devpodman
type Mount struct {
	Source string `json:"source"`

	Target string `json:"target"`

	Type string `json:"type"`
}

// Build configuration options
type BuildOptions struct {
	// Target stage in a multi-stage build.
	Target string `json:"target,omitempty"`

	// Build arguments.
	Args map[string]string `json:"args,omitempty"`

	// The image to consider as a cache. Use an array to specify
	// multiple images.
	CacheFrom []string `json:"cacheFrom,omitempty"`

	// The location of the Dockerfile that defines the contents of the
	// container. The path is relative to the folder containing the
	// `devcontainer.json` file.
	Dockerfile string `json:"dockerfile"`

	// The location of the context folder for building the Docker
	// image. The path is relative to the folder containing the
	// `devcontainer.json` file.
	Context string `json:"context,omitempty"`
}

type DevContainerCommon struct {
	// A name for the dev container.
	Name string `json:"name,omitempty"`

	// Features to add to the dev container.
	Features map[string]any/* CUE top */ `json:"features,omitempty"`

	// Array consisting of the Feature id (without the semantic
	// version) of Features in the order the user wants them to be
	// installed.
	OverrideFeatureInstallOrder []string `json:"overrideFeatureInstallOrder,omitempty"`

	// Ports that are forwarded from the container to the local
	// machine. Can be an integer port number, or a string of the
	// format "host:port_number".
	ForwardPorts []any/* CUE top */ `json:"forwardPorts,omitempty"`

	PortsAttributes struct {
	} `json:"portsAttributes,omitempty"`

	OtherPortsAttributes struct {
		// Defines the action that occurs when the port is discovered for
		// automatic forwarding
		OnAutoForward string `json:"onAutoForward,omitempty"`

		// Automatically prompt for elevation (if needed) when this port
		// is forwarded. Elevate is required if the local port is a
		// privileged port.
		ElevateIfNeeded bool `json:"elevateIfNeeded,omitempty"`

		// Label that will be shown in the UI for this port.
		Label string `json:"label,omitempty"`

		RequireLocalPort bool `json:"requireLocalPort,omitempty"`

		// The protocol to use when forwarding this port.
		Protocol string `json:"protocol,omitempty"`
	} `json:"otherPortsAttributes,omitempty"`

	// Controls whether on Linux the container's user should be
	// updated with the local user's UID and GID. On by default when
	// opening from a local folder.
	UpdateRemoteUserUID bool `json:"updateRemoteUserUID,omitempty"`

	// Remote environment variables to set for processes spawned in
	// the container including lifecycle scripts and any remote
	// editor/IDE server process.
	RemoteEnv map[string]string `json:"remoteEnv,omitempty"`

	// The username to use for spawning processes in the container
	// including lifecycle scripts and any remote editor/IDE server
	// process. The default is the same user as the container.
	RemoteUser string `json:"remoteUser,omitempty"`

	// A command string or list of command arguments to run on the
	// host machine during initialization, including during container
	// creation and on subsequent starts. The command may run more
	// than once during a given session. This command is run before
	// "onCreateCommand". If this is a single string, it will be run
	// in a shell. If this is an array of strings, it will be run as
	// a single command without shell.
	InitializeCommand []string `json:"initializeCommand,omitempty"`

	// A command to run when creating the container. This command is
	// run after "initializeCommand" and before
	// "updateContentCommand". If this is a single string, it will be
	// run in a shell. If this is an array of strings, it will be run
	// as a single command without shell.
	OnCreateCommand map[string][]string `json:"onCreateCommand,omitempty"`

	// A command to run when creating the container and rerun when the
	// workspace content was updated while creating the container.
	// This command is run after "onCreateCommand" and before
	// "postCreateCommand". If this is a single string, it will be
	// run in a shell. If this is an array of strings, it will be run
	// as a single command without shell.
	UpdateContentCommand map[string][]string `json:"updateContentCommand,omitempty"`

	// A command to run after creating the container. This command is
	// run after "updateContentCommand" and before
	// "postStartCommand". If this is a single string, it will be run
	// in a shell. If this is an array of strings, it will be run as
	// a single command without shell.
	PostCreateCommand map[string][]string `json:"postCreateCommand,omitempty"`

	// A command to run after starting the container. This command is
	// run after "postCreateCommand" and before "postAttachCommand".
	// If this is a single string, it will be run in a shell. If this
	// is an array of strings, it will be run as a single command
	// without shell.
	PostStartCommand map[string][]string `json:"postStartCommand,omitempty"`

	// A command to run when attaching to the container. This command
	// is run after "postStartCommand". If this is a single string,
	// it will be run in a shell. If this is an array of strings, it
	// will be run as a single command without shell.
	PostAttachCommand map[string][]string `json:"postAttachCommand,omitempty"`

	// The user command to wait for before continuing execution in the
	// background while the UI is starting up. The default is
	// "updateContentCommand".
	WaitFor string `json:"waitFor,omitempty"`

	// User environment probe to run. The default is
	// "loginInteractiveShell".
	UserEnvProbe string `json:"userEnvProbe,omitempty"`

	// Host hardware requirements.
	HostRequirements struct {
		// Number of required CPUs.
		Cpus int64 `json:"cpus,omitempty"`

		// Amount of required RAM in bytes. Supports units tb, gb, mb and
		// kb.
		Memory string `json:"memory,omitempty"`

		// Amount of required disk space in bytes. Supports units tb, gb,
		// mb and kb.
		Storage string `json:"storage,omitempty"`

		Gpu any/* CUE top */ `json:"gpu,omitempty"`
	} `json:"hostRequirements,omitempty"`

	// Tool-specific configuration. Each tool should use a JSON object
	// subproperty with a unique name to group its customizations.
	Customizations map[string]any/* CUE top */ `json:"customizations,omitempty"`

	AdditionalProperties map[string]any/* CUE top */ `json:"additionalProperties,omitempty"`
}

type DockerfileContainer struct {
	// Docker build-related options.
	Build BuildOptions `json:"build"`
}

type ImageContainer struct {
	// The docker image that will be used to create the container.
	Image string `json:"image"`
}

type NonComposeBase struct {
	// Application ports that are exposed by the container. Is passed to Docker
	// unchanged. Can be used to map ports differently, e.g. "8000:8010".
	AppPort []string `json:"appPort,omitempty"`

	// Container environment variables.
	ContainerEnv map[string]string `json:"containerEnv,omitempty"`

	// The user the container will be started with. The default is the
	// user on the Docker image.
	ContainerUser string `json:"containerUser,omitempty"`

	// Mount points to set up when creating the container.
	Mounts []Mount `json:"mounts,omitempty"`

	// The arguments required when starting in the container.
	RunArgs []string `json:"runArgs,omitempty"`

	// Action to take when the user disconnects from the container in
	// their editor. The default is to stop the container.
	ShutdownAction string `json:"shutdownAction,omitempty"`

	Privileged bool `json:"privileged,omitempty"`

	// Whether to overwrite the command specified in the image. The
	// default is true.
	OverrideCommand bool `json:"overrideCommand,omitempty"`

	// The path of the workspace folder inside the container.
	WorkspaceFolder string `json:"workspaceFolder,omitempty"`

	// The --mount parameter for docker run. The default is to mount
	// the project folder at /workspaces/$project.
	WorkspaceMount Mount `json:"workspaceMount,omitempty"`
}
