USERID=2000
GROUPID=2000
USERNAME=tools
GOLANG_TAG=go1.27.1
GOLANG_HASH=63d339f0da5ab53635a56f2490a7984dfe12dfcff22ad749f63edaf590168445
GOLANG_URL=https://go.dev/dl/go1.27.1.linux-amd64.tar.gz?mode=json
KUBECTL_IMAGE=registry.k8s.io/kubectl-amd64:v1.35.6
KYVERNO_KYVERNO_TAG=v1.19.1
KYVERNO_KYVERNO_URL=https://api.github.com/repos/kyverno/kyverno/releases/assets/408272587
STR4D_AGE_PLUGIN_YUBIKEY_URL=https://api.github.com/repos/str4d/age-plugin-yubikey/releases/assets/183756217
STR4D_AGE_PLUGIN_YUBIKEY_TAG=v0.5.0
GETSOPS_SOPS_TAG=v3.13.3
GETSOPS_SOPS_URL=https://api.github.com/repos/getsops/sops/releases/assets/486808201
GETSOPS_SOPS_HASH=e5bec3346a873ae91d871550f3e698c1aad962aff462a080e40f25fde17fef6b
OPENTOFU_OPENTOFU_TAG=v1.12.6
OPENTOFU_OPENTOFU_URL=https://api.github.com/repos/opentofu/opentofu/releases/assets/520762723
OPENTOFU_OPENTOFU_HASH=50a6106fa4de523d09c87af85f3db1dd47535fc005727fdca6852146476b88ec
CONTAINERS_PODMAN_TAG=v6.1.2
CONTAINERS_PODMAN_URL=https://api.github.com/repos/podman-container-tools/podman/releases/assets/566771156
CONTAINERS_PODMAN_HASH=6785e4dc11dad67000308749fed0f981698792309830a6b870bd5a97b3527182
STACKEXCHANGE_DNSCONTROL_TAG=v5.2.0
STACKEXCHANGE_DNSCONTROL_URL=https://api.github.com/repos/DNSControl/dnscontrol/releases/assets/581809152
STACKEXCHANGE_DNSCONTROL_HASH=9b82d5734af489013a733de991ccd557dcaeebe1631dcc842e4123bb93acc612
CHMLN_SD_TAG=v1.1.0
CHMLN_SD_URL=https://api.github.com/repos/chmln/sd/releases/assets/362325296
DNSCRYPT_DOH_SERVER_TAG=0.9.16
DNSCRYPT_DOH_SERVER_URL=https://api.github.com/repos/DNSCrypt/doh-server/releases/assets/411111405
FLUXCD_FLUX2_TAG=v2.9.5
FLUXCD_FLUX2_URL=https://api.github.com/repos/fluxcd/flux2/releases/assets/538282891
FLUXCD_FLUX2_HASH=b853df82adfd7736f580692f9f734473d571606307139f8fd20c2a80dd1ff473
K0SPROJECT_K0SCTL_TAG=v0.33.1
K0SPROJECT_K0SCTL_URL=https://api.github.com/repos/k0sproject/k0sctl/releases/assets/578938984
K0SPROJECT_K0SCTL_HASH=bd5cd9125c93d8d30c33f7b2f3693fed0d74140a248d433dad74f2b7015295b5
ASTRAL_SH_UV_TAG=0.12.18
ASTRAL_SH_UV_URL=https://api.github.com/repos/astral-sh/uv/releases/assets/582430671
ASTRAL_SH_UV_HASH=89eadd7c76fc063887959510d5ba0ab1264dfd5f1143b925ddb73021a40acf16
NIULE_EU_HLCLI_TAG=v0.0.10
NIULE_EU_HLCLI_URL=https://api.github.com/repos/niule-eu/hlcli/releases/assets/423075363
NIULE_EU_HLCLI_HASH=57d60f563eddab50041f553fe82173b1af744c7ffab67292e4478a401a8fe993
NIULE_EU_SYMAT_TAG=v0.0.26
NIULE_EU_SYMAT_URL=https://api.github.com/repos/niule-eu/symat/releases/assets/490304421
NIULE_EU_SYMAT_HASH=
CUE_LANG_CUE_TAG=v0.17.1
CUE_LANG_CUE_URL=https://api.github.com/repos/cue-lang/cue/releases/assets/479014346
MIKEFARAH_YQ_TAG=v4.53.6
MIKEFARAH_YQ_TAG_NO_V=4.53.6
MIKEFARAH_YQ_URL=https://api.github.com/repos/mikefarah/yq/releases/assets/522028022
RANCHER_CLI_TAG=v2.15.1
RANCHER_CLI_URL=https://api.github.com/repos/rancher/cli/releases/assets/533660395
RANCHER_CLI_HASH=0d2bdce13a55204e97134d894adafdb3be43d3a70290cfb0d56db6c61b913be3
