USERID=2000
GROUPID=2000
USERNAME=tools
GOLANG_TAG=go1.26.1
GOLANG_HASH=031f088e5d955bab8657ede27ad4e3bc5b7c1ba281f05f245bcc304f327c987a
GOLANG_URL=https://go.dev/dl/go1.26.1.linux-amd64.tar.gz?mode=json
KUBECTL_IMAGE_1_34_2=registry.k8s.io/kubectl-amd64:v1.34.2
GETSOPS_SOPS_TAG=v3.12.2
GETSOPS_SOPS_URL=https://api.github.com/repos/getsops/sops/releases/assets/376249998
GETSOPS_SOPS_HASH=14e2e1ba3bef31e74b70cf0b674f6443c80f6c5f3df15d05ffc57c34851b4998
APPLE_PKL_TAG=0.31.1
APPLE_PKL_URL=https://api.github.com/repos/apple/pkl/releases/assets/382243719
OPENTOFU_OPENTOFU_TAG=v1.11.5
OPENTOFU_OPENTOFU_URL=https://api.github.com/repos/opentofu/opentofu/releases/assets/354856986
OPENTOFU_OPENTOFU_HASH=e73868ab8abaca15d3c974dcf6a5e878860d6f2212867433aa3d8f2b43a492d9
CONTAINERS_PODMAN_TAG=v5.8.1
CONTAINERS_PODMAN_URL=https://api.github.com/repos/containers/podman/releases/assets/371791187
CONTAINERS_PODMAN_HASH=8ec4f86bb7f724778ed4065a79982aa2725713a3cf96d41fffb5306fca336cf4
STACKEXCHANGE_DNSCONTROL_TAG=v4.36.1
STACKEXCHANGE_DNSCONTROL_URL=https://api.github.com/repos/StackExchange/dnscontrol/releases/assets/369451562
STACKEXCHANGE_DNSCONTROL_HASH=82a759ce702744e0588276f802a000b878a0c296ee70da333bd4392bed740523
CHMLN_SD_TAG=v1.1.0
CHMLN_SD_URL=https://api.github.com/repos/chmln/sd/releases/assets/362325296
DNSCRYPT_DOH_SERVER_TAG=0.9.15
DNSCRYPT_DOH_SERVER_URL=https://api.github.com/repos/DNSCrypt/doh-server/releases/assets/300090753
FLUXCD_FLUX2_TAG=v2.8.3
FLUXCD_FLUX2_URL=https://api.github.com/repos/fluxcd/flux2/releases/assets/375001601
FLUXCD_FLUX2_HASH=e8b3f87ae73f37656af087cec1bd82ce9034860c2a5d427042d2ee9135fcc8bc
K0SPROJECT_K0SCTL_TAG=v0.29.0
K0SPROJECT_K0SCTL_URL=https://api.github.com/repos/k0sproject/k0sctl/releases/assets/381940563
K0SPROJECT_K0SCTL_HASH=37bfa438cacffeefe2777c09d00f834665a4b8a57d41b4fe28fbd3804e4166a2
ASTRAL_SH_UV_TAG=0.11.3
ASTRAL_SH_UV_URL=https://api.github.com/repos/astral-sh/uv/releases/assets/386561626
ASTRAL_SH_UV_HASH=c0f3236f146e55472663cfbcc9be3042a9f1092275bbe3fe2a56a6cbfd3da5ce
NIULE_EU_HLCLI_TAG=v0.0.9
NIULE_EU_HLCLI_URL=https://api.github.com/repos/niule-eu/hlcli/releases/assets/363297188
NIULE_EU_HLCLI_HASH=0d38cc4d9a500470f77f285dfe33e64b32aa50dbe9274370271b63d10b777511