USERID=2000
GROUPID=2000
USERNAME=tools
GOLANG_TAG=go1.26.4
GOLANG_HASH=1153d3d50e0ac764b447adfe05c2bcf08e889d42a02e0fe0259bd47f6733ad7f
GOLANG_URL=https://go.dev/dl/go1.26.4.linux-amd64.tar.gz?mode=json
KUBECTL_IMAGE=registry.k8s.io/kubectl-amd64:v1.35.6
KYVERNO_KYVERNO_TAG=v1.18.0
KYVERNO_KYVERNO_URL=https://api.github.com/repos/kyverno/kyverno/releases/assets/408272587
GETSOPS_SOPS_TAG=v3.13.2
GETSOPS_SOPS_URL=https://api.github.com/repos/getsops/sops/releases/assets/461838689
GETSOPS_SOPS_HASH=154dfe4cd70554bdd82b98e4cd4acf191d43d01ead6f00a73477aa44c4ac42ef
APPLE_PKL_TAG=0.31.1
APPLE_PKL_URL=https://api.github.com/repos/apple/pkl/releases/assets/382243719
OPENTOFU_OPENTOFU_TAG=v1.12.3
OPENTOFU_OPENTOFU_URL=https://api.github.com/repos/opentofu/opentofu/releases/assets/451267210
OPENTOFU_OPENTOFU_HASH=f87d45408dcbb963ddbe10b2f75e55b3495310556e05c35765dfd5913551f182
CONTAINERS_PODMAN_TAG=v5.8.2
CONTAINERS_PODMAN_URL=https://api.github.com/repos/podman-container-tools/podman/releases/assets/396393573
CONTAINERS_PODMAN_HASH=88f7c21e8399a8f5edd1ef7b5c2e12b29706d0a4f24463f264a0e88d887ebbbf
STACKEXCHANGE_DNSCONTROL_TAG=v4.42.0
STACKEXCHANGE_DNSCONTROL_URL=https://api.github.com/repos/DNSControl/dnscontrol/releases/assets/451495929
STACKEXCHANGE_DNSCONTROL_HASH=5766c35f25b6a913e34b0128d49172cc1855148d42a6097d6219c939cdfd23ac
CHMLN_SD_TAG=v1.1.0
CHMLN_SD_URL=https://api.github.com/repos/chmln/sd/releases/assets/362325296
DNSCRYPT_DOH_SERVER_TAG=0.9.16
DNSCRYPT_DOH_SERVER_URL=https://api.github.com/repos/DNSCrypt/doh-server/releases/assets/411111405
FLUXCD_FLUX2_TAG=v2.9.0
FLUXCD_FLUX2_URL=https://api.github.com/repos/fluxcd/flux2/releases/assets/462295343
FLUXCD_FLUX2_HASH=7aa9779fc7ec6d030e609dab7dbed8c6fc9e3a7f4670834ad02369268aaf341f
K0SPROJECT_K0SCTL_TAG=v0.32.0
K0SPROJECT_K0SCTL_URL=https://api.github.com/repos/k0sproject/k0sctl/releases/assets/465140734
K0SPROJECT_K0SCTL_HASH=89568e506bec81a4c84519ab1bffb5f1aa96d94a1863397ee186ec58dac09452
ASTRAL_SH_UV_TAG=0.11.26
ASTRAL_SH_UV_URL=https://api.github.com/repos/astral-sh/uv/releases/assets/462248295
ASTRAL_SH_UV_HASH=6426a73c3837e6e2483ee344cbc00f36394d179afcba6183cb77437e67db4af0
NIULE_EU_HLCLI_TAG=v0.0.10
NIULE_EU_HLCLI_URL=https://api.github.com/repos/niule-eu/hlcli/releases/assets/423075363
NIULE_EU_HLCLI_HASH=57d60f563eddab50041f553fe82173b1af744c7ffab67292e4478a401a8fe993
NIULE_EU_SYMAT_TAG=v0.0.18
NIULE_EU_SYMAT_URL=https://api.github.com/repos/niule-eu/symat/releases/assets/456589541
NIULE_EU_SYMAT_HASH=
CUE_LANG_CUE_TAG=v0.17.0
CUE_LANG_CUE_URL=https://api.github.com/repos/cue-lang/cue/releases/assets/461081559
MIKEFARAH_YQ_TAG=v4.53.3
MIKEFARAH_YQ_TAG_NO_V=4.53.3
MIKEFARAH_YQ_URL=https://api.github.com/repos/mikefarah/yq/releases/assets/440146735